### ISSUE TITLE
Mack - Add Account Engagement Tracking Code to Mack Trucks Website

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#493]
**Description**
The AE tracking code will enable us to be able to track the user engagement in the site and to be able to review these engagements in MCAE (Marketing Cloud Account Engagement).
The code will need to be provided from the MCAE team and the development team would need to place it before the body close tag on every page. If the tracking code can be embedded in the backend, then it would be dynamically added to all pages. 

**Use case:** User Engagement in Mack Truck websites
As a marketer, I would like to see the user engagement for each page
Then I can review which pieces of content resonates and which ones don't
And then I can craft campaigns which pick up on user engagement patterns

**Acceptance Criteria**
- [x] Correct tracking code has been provided from the MCAE team
`<script type="text/javascript"> piAId = '1039343'; piCId = '122594'; piHostname = 'pi.pardot.com'; (function() {       function async_load(){             var s = document.createElement('script'); s.type = 'text/javascript';             s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';             var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);       }       if(window.attachEvent) { window.attachEvent('onload', async_load); }       else { window.addEventListener('load', async_load, false); } })(); </script>`
- [x] Tracking code is embedded throughout the site, before the body close tag of every page
- [x] Check if the user has accepted targeting cookies to track him/her

**Comment by KJohnsn** [comment]
The following 3rd party tracking script needs to be added to all pages of the Mack Trucks website.  Copy and paste this Javascript code right before the close body tag on your HTML pages. 

<script type="text/javascript">
piAId = '1039343';
piCId = '122594';
piHostname = 'pi.pardot.com';

(function() {
      function async_load(){
            var s = document.createElement('script'); s.type = 'text/javascript';
            s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
            var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
      }
      if(window.attachEvent) { window.attachEvent('onload', async_load); }
      else { window.addEventListener('load', async_load, false); }
})();
</script>

**Comment by BeckyMedlin** [comment]
This work needs to be done after the microsite work.

**Comment by BeckyMedlin** [comment]
@shirin27 Please add to refinement

**Comment by shirin27** [comment]
@KJohnsn how would cookie acceptance impact running this code? Could we specify this?

**Comment by KJohnsn** [comment]
@shirin27 I spoke with Ryan and he has provided a link to provide more details regarding first party tracking > https://help.salesforce.com/s/articleView?id=sf.pardot_admin_first_party_cookie_parent.htm&type=5
We use first-party tracking. IF they are in MCAE and we have an email address and they have consented, we track the webpages they have visited. If we do not have an email address and they have not consented, then it's tracked as a visitor and the ip address is deleted after two weeks if not associated with an email address.
We would like to add a MCAE script to the website to allow MCAE to track leads who have consented to marketing.

<script type="text/javascript">
piAId = '1039343';
piCId = '122594';
piHostname = 'pi.pardot.com';
 
(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, closing the ticket.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/3fd0776c-312f-42cb-8702-e163e38eba94)
