### ISSUE TITLE
FR: V2 Pull Quote

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#767]
### Context/Description

As a Mack Trucks content editor, I want to include larger gold text blocks within my article text
so that important items can stand out effectively and attract readers' attention.

### Acceptance Criteria

**User AC:**
- [ ] As a website user, I can see gold text that stands out on an article page. 

**Editor AC:**
- [x] As an editor, I can use this block on any page.
- [ ] As an editor, I can find this block in the AEM Sidekick library. 
- [x] As an editor, I can insert this block within the article text.

**Non-functional AC:**
- [x] The block will be named: v2-pull-quote
- [x] The block can be used in #603 
- [x] The text color will be Primary Gold #87754E 
- [x] The text font will be "GT America"
- [x] The text size is specified in [Mack Core Design Kit](https://www.figma.com/design/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?node-id=4865-5132&m=dev) 
- [ ] The text block will have the following padding surrounding it so that it can be in line with the #754  
   - Desktop: Left: 40px, above: 40px, right: 138 px, below: 32px. 
   - Mobile: Left: 16px, above: 32px, right: 110 px, below: 24px. 

### Note

Open questions 
- the line that borders the quote is only present on desktop and mobile, is this actually required at all? It is shown with a line in one article but not in another example. 
- Confirming font size with Matt - update NFR 
- Confirm block name
- Old colour #B3976B

### Attachment / link to Figma

Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=14119-2346&t=YBNuoD7kznnR07FV-1

![Image](https://github.com/user-attachments/assets/0bce5637-c95a-4342-a770-b2e13702dc74)

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2222-52861&t=YBNuoD7kznnR07FV-1

![Image](https://github.com/user-attachments/assets/539b5843-66df-4cb1-8c4c-1c8f3aaebbd0)

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Has this been added to the AEM Sidekick library yet?

**Comment by ZoeBeykirch** [comment]
@mollyaljenkins @jonatan-lledo-netcentric I just checked the library, and do not see the new block here: https://main--vg-macktrucks-com--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks
