### ISSUE TITLE
NFR: Mack Trucks Helix5 Upgrade Steps (1 of 2)

### ISSUE THREAD

**Issue by mollyaljenkins** [hlxsites/vg-macktrucks-com#900]
### Context/Description
Required steps to upgrade to the new Helix 5 for Mack Trucks

### Acceptance Criteria
Adobe AC:
@dkuntze:
- [x] Point existing DNS to new Helix 5
First Six Repo Upgrade: 

- https://www.macktrucks.com/
- https://www.macktrucks.ca/
- https://www.macktrucks.com.mx/
- https://www.macktrucks.com.au/ | not done
- https://www.macktrucks.co.nz/
- https://www.macktrucks.com.co/

### Non-functional AC:
- [x] Update the new repo code with the changes from the upstream repo
- [ ] Detach the new repo from the upstream, a manual request needs to be request to GitHub support
- [ ] Search functionality needs to be connected with the proper dev endpoints (same endpoint as in VT)
- [ ] Test Search and the publish and unpublished workflows
- [x] The change done in this [commit](https://github.com/hlxsites/vg-macktrucks-com/commit/b09e5ac9b02d91cd3011319dcfab41030aaa57aa) needs to be replicated in the helix config bus since in the new repo the helix-query.yaml file doesn't exist
- [x] Test the feed generation

### Phase 1 Mack Markets for Upgrade
- https://www.macktrucks.com/
- https://www.macktrucks.ca/
- https://www.macktrucks.com.mx/
- https://www.macktrucks.com.au/
- https://www.macktrucks.co.nz/
- https://www.macktrucks.com.co/

### Out of scope
- [x] Transfer issues from the old repo to the new repo
- [x] #906

### All Mack Sites 
https://www.macktrucks.com/
https://www.macktrucks.ca/
https://www.macktrucks.com.mx/
https://www.macktrucks.com.au/
https://www.macktrucks.co.nz/
https://www.macktrucks.com.co/
https://www.macktrucks.com.ar/
https://www.macktrucks.com.bo/
https://www.macktrucks.cl/
https://www.macktrucks.com.ec/
https://www.macktrucksguyana.com/
https://www.macktrucks.com.pe/
https://www.macktrucks.com.ve/
https://www.macktrucks.com.do/
https://www.macktrucks.ht/
https://www.macktrucks.cr/
https://www.macktrucks.gt/
https://www.macktrucks.hn/
https://www.macktrucksnicaragua.com/
https://www.macktrucks.com.pa/
https://www.macktrucksemea.com/
https://tt.macktrucks.com/
https://bahamas.macktrucks.com/
https://sv.macktrucks.com/
https://www.macktrucksnigeria.com/
https://www.macktruckshistoricalmuseum.org/

**Comment by BeckyMedlin** [comment]
Mack Trucks MX site was down after upgrade to Helix5. After troubleshooting with Darin, he advised that we have to sort out the cdn purge when we make the change to the new urls.

**Comment by alexiscoelho** [comment]
We encounter an issue with the Australian Mack Trucks website. Hence, the Australian website will have to wait for the phase 2 release.
